site_name: Watchman
nav:
    - 'Strona główna': index.md
    - 'Lista funkcjonalności': 156-lista-funkcjonalnosci.md
    - 'Instrukcja dla nowych osób w zespole Watchmana': 150-instrukcja-dla-nowych-osob-w-zespole-watchmana.md
    - 'Jak zacząć rozwijać bota': 151-jak-zaczac-rozwijac-bota.md
    - 'Dokumentacja techniczna':
        - 'Serwisy w frameworku': 135-services-in-framework.md
        - 'Jak działa Workflow': 134-workflow.md
        - 'Do czego używamy klasy Server': 141-do-czego-uzywamy-klasy-server.md
theme: 
    name: 'material'
    language: pl
    font:
        text: Roboto
        code: Roboto
    features:
        - tabs
        - instant
    palette:
        primary: 'green'
        accent: 'light green'
markdown_extensions:
    - codehilite
extra_css:
  - stylesheets/codehilite.css
